### ISSUE TITLE
Payment Express Hosted Payment Solution - PxPay 2.0

### ISSUE THREAD

**Issue by sunrise-xx** [DerManoMann/dps-pxpay#6]
Dears,
Now PaymentExpress PxPay  have new update, I want to know whether your module have update?

https://www.paymentexpress.com/Technical_Resources/Ecommerce_Hosted/PxPay_2_0
https://www.paymentexpress.com/Products/Ecommerce/Account2Account

https://www.paymentexpress.com/Products/Ecommerce/Payment_Express_Hosted

Thanks & Best Regards,
Sunrise

**Comment by DerManoMann** [comment]
Short answer is no. Long answer is that I do not have any plans of working on this module in the near future; sorry.

**Comment by DerManoMann** [comment]
closing as wontfix
